module m41.game.generation.models.depthcylinder;

private {
	import noise.mathconsts;
	import std.math;
	import noise.mod.modulebase;
	import noise.model.cylinder;
}

class DepthCylinder : Cylinder {

	/// Returns the output value from the noise module given the
	/// (angle, height) coordinates of the specified input value located
	/// on the surface of the cylinder.
	///
	/// @param angle The angle around the cylinder's center, in degrees.
	/// @param height The height along the @a y axis.
	///
	/// @returns The output value from the noise module.
	///
	/// @pre A noise module was passed to the SetMod() method.
	///
	/// This output value is generated by the noise module passed to the
	/// SetMod() method.
	///
	/// This cylinder has a radius of 1.0 unit and has infinite height.
	/// It is oriented along the @a y axis.  Its center is located at the
	/// origin.
	public final double GetValue (double angle, double radius, double height)
	{
	  assert (m_pMod !is null);

	  double x, y, z;
	  x = radius*cos(angle * DEG_TO_RAD);
	  y = height;
	  z = radius*sin(angle * DEG_TO_RAD);
	  return m_pMod.GetValue (x, y, z);
	}


	/// A pointer to the noise module used to generate the output values.
	private Mod m_pMod;
}